project_id = "pmhktnxqponixycsjcwr"

[functions.discord-health]
verify_jwt = false

[functions.discord-sync]
verify_jwt = false

[functions.discord-user-roles]
verify_jwt = false

[functions.discord-role-counts]
verify_jwt = false

